version: '3.7'
services:

  unbound-app:
    image: unbound
    container_name: unbound-app
    ports:
      - "192.168.0.14:5335:53/tcp"
      - "192.168.0.14:5335:53/udp"            
    cap_add:
      - NET_ADMIN 
    restart: always
